# Generated by Django 4.2.10 on 2024-02-27 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('curso', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_turma', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_professor', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField()),
                ('sobrenome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professores', to='projeto.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id_estudante', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.TextField()),
                ('sobrenome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='projeto.curso')),
                ('id_turma', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='projeto.turma')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField()),
                ('resumo', models.CharField(max_length=255)),
                ('id_professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinas', to='projeto.professor')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='id_disciplina',
            field=models.ManyToManyField(related_name='cursos', to='projeto.disciplina'),
        ),
        migrations.AddField(
            model_name='curso',
            name='id_professor',
            field=models.ManyToManyField(related_name='cursos', to='projeto.professor'),
        ),
    ]
