# Generated by Django 4.2.10 on 2024-03-11 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_disciplina_nome_curso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField()),
                ('nome', models.TextField()),
                ('sobrenome', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('id_curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudantes', to='projeto.curso')),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='id_turma',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='nome_curso',
            field=models.TextField(unique=True),
        ),
        migrations.DeleteModel(
            name='Estudante',
        ),
        migrations.DeleteModel(
            name='Turma',
        ),
    ]
