# Generated by Django 4.2.10 on 2024-03-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0004_aluno_remove_professor_id_turma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='id_curso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='username',
        ),
    ]
