# Generated by Django 4.2.10 on 2024-03-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_remove_curso_id_disciplina_remove_curso_id_professor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoEDisciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cursos', to='projeto.curso')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_disc', to='projeto.disciplina')),
            ],
        ),
    ]
