# Generated by Django 4.2.10 on 2024-03-12 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_cursoedisciplina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursoedisciplina',
            name='id_disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_disc_curso', to='projeto.disciplina'),
        ),
        migrations.CreateModel(
            name='AlunoFazDisciplina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_al', to='projeto.aluno')),
                ('id_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_disc_aluno', to='projeto.disciplina')),
            ],
        ),
    ]
