# Generated by Django 4.2.10 on 2024-03-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_alter_cursoedisciplina_id_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='id_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_prof', to='projeto.professor'),
        ),
    ]
