# Generated by Django 4.2.10 on 2024-03-13 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0009_alter_disciplina_id_professor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aluno',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['curso']},
        ),
        migrations.AlterModelOptions(
            name='disciplina',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'permissions': [('modificar_disciplinas', 'Modifica disciplinas')]},
        ),
    ]
