# Generated by Django 4.2.10 on 2024-03-13 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0011_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ['nome'], 'permissions': [('modificar_disciplinas', 'Pode Modificar Disciplinas')]},
        ),
    ]
